<a href="https://colab.research.google.com/github/Kanmani-CM/Data-science-/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([20,30,60])
b=np.array([1,5,8])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[21 35 68]
[19 25 52]
[ 20 150 480]
[20.   6.   7.5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
import numpy as np
A = np.array([1,2,3,4])
print(A[1:2])
B = np.array([1,3,5,7,9])
print(B[0:4:2])
print(A[:-1])
C = np.array([[1,2,3,4],[5,6,7,8]])
print(C[0][2])

[2]
[1 5]
[1 2 3]
3


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = arr1.view()

arr2[0] = 0
print(arr1)


[0 2 3 4]


In [ ]:
import numpy as np
a=([[[5,6,8],[5,4,3]]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))

31
3
8


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = arr1.view()

arr2[0] = 0
print(arr1)


Original Array: [3 1 4 1 5 9 2 6 5 3 5]
Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]


In [ ]:
import numpy as np


array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])


result = array1 + array2


print("Array 1:", array1)
print("Array 2:", array2)
print("Result of Addition:", result)


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]
Result of Addition: [11 22 33 44 55]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into 2 sub-arrays
sub_arrays = np.split(arr, 2)

print("Original Array:", arr)
print("Sub-Arrays:", sub_arrays)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Sub-Arrays: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [ ]:
import numpy as np

arr = np.array([10,20,30,60,50])

arr[1]=25

print ("Modified array:",arr)


Modified array: [10 25 30 60 50]


In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

vertical_stack = np.vstack((array1, array2))

horizontal_stack = np.hstack((array1, array2))

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

print("Vertical Stack:")
print(vertical_stack)

print("Horizontal Stack:")
print(horizontal_stack)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8  9]
 [10 11 12]]
Vertical Stack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
