<a href="https://colab.research.google.com/github/Kanmani-CM/Data-science-/blob/main/task7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK-4
1)a. Write a NumPy program to convert an array to a float **type**

In [ ]:
import numpy as np

# Create an integer array
int_array = np.array([1, 2, 3, 4, 5])

# Convert the array to float type
float_array = int_array.astype(float)

print("Original array:", int_array)
print("Array with float type:", float_array)


Original array: [1 2 3 4 5]
Array with float type: [1. 2. 3. 4. 5.]


b. Write a NumPy program to add a border (filled with 0's) around an existing array

In [ ]:
import numpy as np

# Create an example array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

# Add a border with 0's around the existing array
array_with_border = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)

print("Existing array:")
print(existing_array)
print("Array with border:")
print(array_with_border)


Existing array:
[[1 2 3]
 [4 5 6]]
Array with border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


c. Write a NumPy program to convert a list and tuple into arrays

In [ ]:
import numpy as np

# Convert a list to array
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)

# Convert a tuple to array
tuple_data = (5, 4, 3, 2, 1)
array_from_tuple = np.array(tuple_data)

print("Array from list:", array_from_list)
print("Array from tuple:", array_from_tuple)


Array from list: [1 2 3 4 5]
Array from tuple: [5 4 3 2 1]


d. Write a NumPy program to append values to the end of an array

In [ ]:
import numpy as np

# Create an initial array
initial_array = np.array([1, 2, 3])

# Values to append
values_to_append = np.array([4, 5, 6])

# Append values to the end of the array
result_array = np.append(initial_array, values_to_append)

print("Initial array:", initial_array)
print("Array after appending values:", result_array)


Initial array: [1 2 3]
Array after appending values: [1 2 3 4 5 6]
